---
title: "clustering"
author: "Sam Goodson"
date: "2024-01-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(janitor)
library(broom)
library(tidycensus)
library(stringr)
library(leaflet)
library(shiny)
```


```{r}
#Read Open Data 
pb_survey <- read.csv('data/raw/Participatory_Budgeting_Survey_Data.csv')
pb_projects <- read.csv('data/raw/Participatory_Budgeting_Projects.csv')
cc_membership <- read.csv('data/raw/NYC_City_Council_Committee_Membership.csv')
cc_con_services <- read.csv('data/raw/NYC_Council_Constituent_Services.csv')
nypd_arrest <- read_csv("data/raw/NYPD_Arrest_Data__Year_to_Date_.csv")
ed_pres <- read.csv('data/raw/ed_pres.csv', colClasses = c("character", "character"))

#Read Shapefiles
cc_map <- read_sf('data/shapefiles/city_council')
nyc_map <- read_sf('data/shapefiles/NYCShapefile/nyct2020_22b')
ed_map <- read_sf('data/shapefiles/ed')

```


```{r}
fetch_and_pivot_data <- function(counties, table) {
  data <- get_acs(
    geography = "tract",
    state = "NY",
    county = counties,
    table = table
  )
  pivoted_data <- pivot_wider(data, names_from = variable, values_from = c(estimate, moe))
  return(pivoted_data)
}

tables_to_fetch <- c('B08301', 'B02001', 'B08303','B05001','B19013','B03002','B25064','B25070')
nyc_counties<-c('005','047','061','081','085')

joined_data <- data.frame()

for (table in tables_to_fetch) {
  table_data <- fetch_and_pivot_data(nyc_counties, table)
  if (nrow(joined_data) == 0) {
    joined_data <- table_data
  } else {
    joined_data <- left_join(joined_data, table_data)
  }
}

```


```{r}
acs<-joined_data%>%
  rename('white' = estimate_B02001_002, 'black' = estimate_B02001_003, 
  'am_ind' = estimate_B02001_004,
  'asian'=estimate_B02001_005,
  'nat_haw' = estimate_B02001_006, 'other' = estimate_B02001_007,
  'whiteNH' = estimate_B03002_003, 'black_eth' = estimate_B03002_004, 
  'am_ind_eth' = estimate_B03002_005,
  'asian_eth'=estimate_B03002_006,
  'nat_haw_eth' = estimate_B03002_007, 'other_eth' = estimate_B03002_008,
  'hispanic' = estimate_B03002_012,
  'bus' = estimate_B08301_011, 'bike' = estimate_B08301_018, 
  'walk' = estimate_B08301_019,
  'subway' = estimate_B08301_012,'car' = estimate_B08301_002,
  'citizen' = estimate_B05001_002,'citizenPR' = estimate_B05001_003,
  'citizenBA'=estimate_B05001_004, 'naturalized' = estimate_B05001_005,
  'noncit' = estimate_B05001_006,
  'mhi' = estimate_B19013_001, 'med_rent' = estimate_B25064_001)

acs$transpo_all<-acs$estimate_B08303_001
acs$perc_bus<-((acs$bus/acs$transpo_all)*100)
acs$perc_subway<-((acs$subway/acs$transpo_all)*100)

acs<-acs%>%
separate(NAME,c('Tract','County','State'), sep = ",")

acs<-acs%>%
rename('total_pop' = estimate_B03002_001)
```


```{r}
acs<-acs%>%
  mutate(perc_white = round((whiteNH/total_pop)*100),
         perc_hisp = round((hispanic/total_pop)*100),
         perc_black = round((black_eth/total_pop)*100),
         perc_asian = round((asian_eth/total_pop)*100))

acs<-acs%>%
  mutate(transit = (bus + subway),
         no_car = (bus + subway + walk + bike),
         trans_min_car = ((bus+subway)-car),
         no_car_min = ((bus + subway + walk + bike) - car))

acs<-acs%>%
  mutate(avg_com = ((estimate_B08303_002*5) + (estimate_B08303_003*9) + 
                      (estimate_B08303_004*14) + (estimate_B08303_005*19) + 
                      (estimate_B08303_006* 24) + (estimate_B08303_007*29) +
                      (estimate_B08303_008 *34) + (estimate_B08303_009*39) +
                      (estimate_B08303_010*44) + (estimate_B08303_011*59) + 
                      (estimate_B08303_012 * 89) + 
                      (estimate_B08303_013*110))/(estimate_B08301_001+1))
```


```{r}
# Join acs with shapefile
acs_map <- left_join(nyc_map, acs)

acs_cc_map <- st_join(acs_map, cc_map, join = st_within)

# Drop every col that begins with moe
acs_cc_map <- acs_cc_map %>%
  select(-starts_with("moe"))

# Drop every col that begins with estimate
acs_cc_map <- acs_cc_map %>%
  select(-starts_with("estimate"))

acs_cc_map$CDTA2020 <- str_remove_all(acs_cc_map$CDTA2020, "[^0-9]")
acs_cc_map$CDTA2020 <- as.numeric(acs_cc_map$CDTA2020)
```

```{r}
# Convert nypd datat to sf object and join
nypd_arrest_sf <- st_as_sf(nypd_arrest, coords = c("Longitude", "Latitude"), crs = 4326)

# Transform nypd_arrest_sf to match CRS of acs_cc_map
nypd_arrest_sf_transformed <- st_transform(nypd_arrest_sf, crs = st_crs(acs_cc_map))
```


```{r}
acs_cc_map <- acs_cc_map %>%
  select(- c(Tract))%>%
  group_by(CounDist) %>%
  summarise(perc_bus = mean(perc_bus, na.rm = TRUE),
            perc_subway = mean(perc_subway, na.rm = TRUE),
            perc_white = mean(perc_white, na.rm = TRUE),
            perc_black = mean(perc_black, na.rm = TRUE),
            avg_com = mean(avg_com, na.rm = TRUE),
            mhi = mean(mhi, na.rm = TRUE))
```


```{r}
acs_cc_map_arrest <- st_join(acs_cc_map, nypd_arrest_sf_transformed, join = st_contains)


acs_cc_map_arrest <- acs_cc_map_arrest %>%
select(CounDist,OFNS_DESC)
```


```{r}
acs_cc_map_arrest <- acs_cc_map_arrest %>%
mutate('violent' = if_else(OFNS_DESC %in% c('ASSAULT 3 & RELATED OFFENSES','DANGEROUS WEAPONS',
'FELONY ASSAULT','FELONY SEX CRIMES','HOMICIDE-NEGLIGENT,UNCLASSIFIE','KIDNAPPING & RELATED OFFENSES','KIDNAPPING',
"MURDER & NON-NEGL. MANSLAUGHTE",'RAPE'),1,0))

crime <- acs_cc_map_arrest %>%
  st_drop_geometry()%>%
  group_by(CounDist)%>%
  summarise(v_crime = sum(violent))
```

```{r}
acs_crime <- left_join(acs_cc_map,crime)
```


```{r}
cc_con_services <- cc_con_services%>%
  filter(COUNCIL_DIST > 51)
```

```{r}
cc_con_services$COUNCIL_DIST <- str_remove_all(cc_con_services$COUNCIL_DIST, "[^0-9]")
cc_con_services$COUNCIL_DIST <- as.numeric(cc_con_services$COUNCIL_DIST)

con_serv <- cc_con_services %>%
  select('CounDist' = COUNCIL_DIST, COMPLAINT_TYPE, DESCRIPTOR)
```

```{r}
perc_im_con <- con_serv %>% 
  filter(!is.na(COMPLAINT_TYPE) & COMPLAINT_TYPE != "") %>% 
  group_by(CounDist, COMPLAINT_TYPE) %>% 
  summarise(n = n()) %>% 
  ungroup() %>% 
  pivot_wider(names_from = COMPLAINT_TYPE, values_from = n) %>% 
  mutate(total = rowSums(across(where(is.numeric)), na.rm = TRUE), perc_immigration = ((Immigration/total)*100))%>%
  select(CounDist,perc_immigration)
```

```{r}
perc_im_con$CounDist <- as.integer(perc_im_con$CounDist)

cluster_join <- left_join(acs_crime,perc_im_con)
```

```{r}
ed_pres$ElectDist <- paste0(ed_pres$AD,ed_pres$ED)

ed_pres <- ed_pres %>% 
  select(-c(AD, ED)) %>% 
  group_by(ElectDist) %>% 
  pivot_wider(names_from = Info, values_from = Votes) %>% 
  mutate(across(c("Public Counter", "Absentee / Military", "Affidavit", "Donald J. Trump / Michael R. Pence (Conservative)"), ~ as.numeric(.)),  
         total = `Public Counter` + `Absentee / Military` + Affidavit,
         perc_trump = (`Donald J. Trump / Michael R. Pence (Conservative)`/total)*100) 

ed_pres$ElectDist <- as.numeric(ed_pres$ElectDist)

ed_map_join <- left_join(ed_map,ed_pres)
```

```{r}
ed_rollup <- st_join(cc_map,ed_map_join, join = st_contains)

ed_rollup <- ed_rollup%>%
  st_drop_geometry()%>%
  select(CounDist,perc_trump)%>%
  group_by(CounDist)%>%
  summarize(trump = mean(perc_trump, na.rm = TRUE))%>%
  arrange(desc(trump))

cluster_join <- left_join(acs_crime,ed_rollup)
```

```{r}
cluster <- cluster_join %>%
  st_drop_geometry()%>%
  select(-CounDist)%>%
  na.omit()%>%
  scale()%>%
  as.data.frame()%>%
  kmeans(centers = 5)
```

```{r}
cluster_join<-cluster_join%>%
  drop_na()
cluster_join$cluster <- cluster$cluster

# Join cluster_join with cc_map
cluster_join <- cluster_join%>%
  st_drop_geometry()%>%
  select(-geometry)

cluster_join_map <- left_join(cc_map,cluster_join)
```

```{r}
ggplot() +
  geom_sf(data = cluster_join_map, aes(fill = as.factor(cluster))) +
  scale_fill_viridis_d(option = "plasma", name = "Cluster") +
  theme_void() +
  theme(legend.position = "bottom")
```

